"""is_verified

Revision ID: 16a20fe3c028
Revises: b10dfa913a0f
Create Date: 2024-09-02 12:49:53.170327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a20fe3c028'
down_revision: Union[str, None] = 'b10dfa913a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('verification_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_code')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
